spring:
  datasource:
    username: root
    password: L4826866
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/puthand?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=true
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    druid:
      initial-size: 5
      min-idle: 5
      max-wait: 60000
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
  thymeleaf:
    mode: HTML
    servlet:
      content-type: text/html
    cache: false
    prefix: classpath:/templates/
